version: 2
updates:
  - package-ecosystem: cargo
    directory: /scripts/rust
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: gradle
    directory: /scripts/helper
    schedule:
      interval: monthly
