version: 2
updates:
  - package-ecosystem: cargo
    directory: /computer
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: gradle
    directory: /device
    schedule:
      interval: monthly
