[CmdletBinding()]
param(
  [string]$Root,
  [switch]$Check
)

$ErrorActionPreference = 'Stop'
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
if ([string]::IsNullOrWhiteSpace($Root)) { $Root = Split-Path -Parent $scriptRoot }
$schemaPath = Join-Path $Root 'references\protocol-schema.json'
$contractPath = Join-Path $Root 'references\agent-contract.json'
$bodyPath = Join-Path $Root 'references\skill-static.md'
$outputPath = Join-Path $Root 'skills\android-use\SKILL.md'
$referenceRoot = Join-Path $Root 'references'
$skillReferenceRoot = Join-Path $Root 'skills\android-use\references'

if (-not (Test-Path -LiteralPath $schemaPath -PathType Leaf)) { throw "protocol schema is missing: $schemaPath" }
if (-not (Test-Path -LiteralPath $contractPath -PathType Leaf)) { throw "agent contract is missing: $contractPath" }
if (-not (Test-Path -LiteralPath $bodyPath -PathType Leaf)) { throw "skill static body is missing: $bodyPath" }

$referenceFiles = @(Get-ChildItem -LiteralPath $referenceRoot -File |
  Where-Object { $_.Extension -in @('.md', '.json') })
if ($Check) {
  foreach ($reference in $referenceFiles) {
    $target = Join-Path $skillReferenceRoot $reference.Name
    if (-not (Test-Path -LiteralPath $target -PathType Leaf)) { throw "generated skill reference is missing: $target" }
    if ((Get-FileHash -LiteralPath $reference.FullName -Algorithm SHA256).Hash -ne
        (Get-FileHash -LiteralPath $target -Algorithm SHA256).Hash) {
      throw "generated skill reference is stale: $target"
    }
  }
} else {
  New-Item -ItemType Directory -Force -Path $skillReferenceRoot | Out-Null
  foreach ($reference in $referenceFiles) {
    Copy-Item -LiteralPath $reference.FullName -Destination (Join-Path $skillReferenceRoot $reference.Name) -Force
  }
}

$schema = Get-Content -LiteralPath $schemaPath -Raw | ConvertFrom-Json
$contract = Get-Content -LiteralPath $contractPath -Raw | ConvertFrom-Json
$body = ((Get-Content -LiteralPath $bodyPath -Raw) -replace "`r`n", "`n").Trim()
$schemaHash = (Get-FileHash -LiteralPath $schemaPath -Algorithm SHA256).Hash.ToLowerInvariant()
$contractHash = (Get-FileHash -LiteralPath $contractPath -Algorithm SHA256).Hash.ToLowerInvariant()
$tapeSource = Get-Content -LiteralPath (Join-Path $Root 'crates\android-use\src\tape.rs') -Raw
$opcodeMatch = [regex]::Match($tapeSource, 'pub const OPCODES: &\[char\] = &\[(?<body>.*?)\];', [Text.RegularExpressions.RegexOptions]::Singleline)
if (-not $opcodeMatch.Success) { throw 'tape opcode table is missing from crates\android-use\src\tape.rs' }
$sourceOpcodes = @([regex]::Matches($opcodeMatch.Groups['body'].Value, "'([A-Z])'") | ForEach-Object { $_.Groups[1].Value })
$schemaOpcodes = @($schema.opcodes.psobject.Properties | ForEach-Object { $_.Name.ToUpperInvariant() })
if ((@($sourceOpcodes | Sort-Object) -join ',') -ne (@($schemaOpcodes | Sort-Object) -join ',')) {
  throw "protocol schema opcode table drift: Rust=[$($sourceOpcodes -join ',')] schema=[$($schemaOpcodes -join ',')]"
}
$opcodeRows = @($schema.opcodes.psobject.Properties | Sort-Object Name | ForEach-Object {
  $op = $_.Value
  $args = (@($op.args) -join ', ')
  "| ``$($_.Name)`` | $args | $($op.class) |"
})
$limitRows = @($schema.limits.psobject.Properties | Sort-Object Name | ForEach-Object {
  "``$($_.Name)=$($_.Value)``"
}) -join ', '
$batchRows = @($schema.batch.prefixes.psobject.Properties | Sort-Object Name | ForEach-Object {
  $prefix = $_.Name
  $rule = $_.Value
  "``$prefix N`` (max $($rule.max)): $($rule.meaning)"
}) -join '; '
$diagnosticText = "``$($schema.diagnostics.disassemble)`` (aliases $($schema.diagnostics.aliases -join ', ')): device-free expanded tape decoder"

$frontmatter = @"
---
name: $($schema.skill.name)
description: $($schema.skill.description)
---
"@.Trim()

$generated = @"
## v2 agent contract

This section is generated from ``references/agent-contract.json``. Contract SHA-256: ``$contractHash``. Methods: ``$($contract.methods -join ', ')``. Limits: ``max_steps=$($contract.limits.max_steps)``, ``max_mutations=$($contract.limits.max_mutations)``, ``max_deadline_ms=$($contract.limits.max_deadline_ms)``, ``max_message_bytes=$($contract.limits.max_message_bytes)``.

Use ``android.observe`` before ``android.execute``; plans are semantic, bounded, generation-aware, and proof-carrying. ``E_STALE`` requires a fresh observation. ``E_UNKNOWN_COMMIT`` requires observation before any retry. Raw ADB, raw shell, arbitrary code, unrestricted paths, and unbounded loops are not part of this contract.

## Generated protocol contract

This section is generated by ``scripts/generate-skill.ps1`` from ``references/protocol-schema.json``. Schema SHA-256: ``$schemaHash``. Protocol version: ``$($schema.version)``. Limits: $limitRows.

| Opcode | Operands | Class |
|---|---|---|
$($opcodeRows -join "`n")

Aliases: ``$($schema.aliases -join ', ')``. Dictionary refs: ``$($schema.refs.dictionary)``. Register refs: ``$($schema.refs.register)``. Batch controls: $batchRows. Diagnostic: $diagnosticText. Model output: ``$($schema.output.success)``; binary default: ``$($schema.output.binary_default)``.
"@.Trim()

$content = "$frontmatter`n`n$body`n`n$generated`n"
$content = $content -replace "`r`n", "`n"
$utf8 = [System.Text.UTF8Encoding]::new($false)
if ($Check) {
  if (-not (Test-Path -LiteralPath $outputPath -PathType Leaf)) { throw "generated skill is missing: $outputPath" }
  $current = [IO.File]::ReadAllText($outputPath)
  if ($current -ne $content) { throw "SKILL.md is out of date; run scripts\generate-skill.ps1" }
  Write-Output "skill up to date: $outputPath"
} else {
  New-Item -ItemType Directory -Force -Path (Split-Path -Parent $outputPath) | Out-Null
  [IO.File]::WriteAllText($outputPath, $content, $utf8)
  Write-Output "generated: $outputPath"
}
